"use client";
import {X, Check, AlertTriangle, Info} from "lucide-react";
export function Button({children,variant="primary",className="",...props}:any){const c=variant==="primary"?"bg-[var(--primary)] text-white hover:opacity-90":variant==="danger"?"bg-[var(--danger)] text-white":variant==="ghost"?"bg-transparent hover:bg-black/5 dark:hover:bg-white/5":"border border-[var(--border)] bg-[var(--surface)] hover:bg-black/5 dark:hover:bg-white/5";return <button className={`min-h-10 rounded-xl px-4 text-sm font-semibold transition ${c} ${className}`} {...props}>{children}</button>}
export function Card({children,className=""}:any){return <div className={`rounded-2xl border border-[var(--border)] bg-[var(--surface)] ${className}`}>{children}</div>}
export function Input({label,...props}:any){return <label className="block space-y-1.5 text-sm"><span className="font-medium">{label}</span><input className="w-full min-h-11 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 outline-none focus:border-[var(--primary)]" {...props}/></label>}
export function Select({label,children,...props}:any){return <label className="block space-y-1.5 text-sm"><span className="font-medium">{label}</span><select className="w-full min-h-11 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 outline-none focus:border-[var(--primary)]" {...props}>{children}</select></label>}
export function Textarea({label,...props}:any){return <label className="block space-y-1.5 text-sm"><span className="font-medium">{label}</span><textarea className="w-full min-h-24 rounded-xl border border-[var(--border)] bg-[var(--surface)] px-3 py-2 outline-none focus:border-[var(--primary)]" {...props}/></label>}
export function Badge({children,tone="neutral"}:any){const map:any={success:"bg-[color-mix(in_srgb,var(--success)_16%,transparent)] text-[var(--success)]",warning:"bg-[color-mix(in_srgb,var(--warning)_16%,transparent)] text-[var(--warning)]",danger:"bg-[color-mix(in_srgb,var(--danger)_16%,transparent)] text-[var(--danger)]",neutral:"bg-black/5 dark:bg-white/10"};return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-semibold ${map[tone]}`}>{children}</span>}
export function Modal({title,children,onClose,footer}:any){return <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center bg-black/35 p-3 sm:p-6" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><div className="w-full max-w-xl max-h-[90vh] overflow-auto rounded-3xl border border-[var(--border)] bg-[var(--surface)] shadow-2xl"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-[var(--border)] bg-[var(--surface)] px-5 py-4"><h2 className="serif text-xl font-semibold">{title}</h2><button aria-label="Cerrar" onClick={onClose} className="rounded-full p-2 hover:bg-black/5"><X size={20}/></button></div><div className="p-5">{children}</div>{footer&&<div className="flex justify-end gap-2 border-t border-[var(--border)] p-4">{footer}</div>}</div></div>}
export function Toast({message,onClose}:any){return <div className="fixed bottom-24 right-4 z-[60] flex items-center gap-2 rounded-2xl border border-[var(--border)] bg-[var(--surface)] px-4 py-3 shadow-xl"><Check size={18} className="text-[var(--success)]"/><span className="text-sm font-medium">{message}</span><button onClick={onClose}><X size={16}/></button></div>}
export function EmptyState({title,text,action}:any){return <div className="flex flex-col items-center justify-center py-14 text-center"><div className="mb-3 rounded-2xl bg-[var(--bg)] p-4"><Info size={28} className="text-[var(--primary)]"/></div><h3 className="font-semibold">{title}</h3><p className="mt-1 max-w-sm text-sm text-[var(--muted)]">{text}</p>{action&&<div className="mt-4">{action}</div>}</div>}
export function StockAlert({name,stock,unit}:any){return <div className="flex items-center gap-3 rounded-xl border border-[var(--border)] p-3"><AlertTriangle size={18} className="text-[var(--warning)]"/><div><div className="text-sm font-semibold">Stock bajo</div><div className="text-xs text-[var(--muted)]">{name}: {stock} {unit}</div></div></div>}
